# prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets by default

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093 # Update if you have Alertmanager setup

# Scrape configurations
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "directus"
    static_configs:
      - targets: ["directus:8055"]
